'use strict'

console.log('linked puzzles.js');

const puzzleArray = ['DAIRY QUEEN OF HEARTS', 'CLASH OF THE TITANS', 'CHOCOLATE MACADAMIA NUT COOKIES', 'DELICIOUS DECADENT DESSERTS', 'CASHING IN A HUGE STACK OF CHIPS', 'ALL-DAY SKI LIFT TICKETS', 'CASABLANCA MOROCCO', 'THE VIEW FROM THE TOP OF A MOUNTAIN', 'PERSONALIZED STATIONERY', 'ST. ELMO\'S FIRE EXTINGUISHER', 'MONKEY BUSINESS PROPOSITION', 'LIGHTS CAMERA ACTION FIGURES', 'LUNCH WILL BE SERVED POOLSIDE', 'MANDATORY MONDAY MORNING MEETING', 'MYTHOLOGICAL HERO HERCULES', 'CHARIOTS OF FIRE HYDRANTS', 'NO-PARKING & TWILIGHT ZONE', 'COMMEMORATIVE COIN COLLECTION', 'FINDERS KEEPERS LOSERS WEEPERS', 'WRITING WISH YOU WERE HERE ON A POSTCARD', 'SUGGESTION BOX OF DONUTS', 'THE PRICE IS RIGHT TO REMAIN SILENT', 'THE CONTINENT OF ANTARCTICA', 'RINGING IN THE NEW YEAR IN TIMES SQUARE', 'THESE ARE A FEW OF MY FAVORITE THINGS', 'BREAKING A NEW YEAR\'S RESOLUTION', 'STRUMMING A SONG ON A UKULELE', 'SENSATIONAL SUBMARINE SANDWICH', 'INVIGORATING MORNING SWIM'];

// const puzzleArray = ['ALL-DAY SKI LIFT TICKETS', 'ST. ELMO\'S FIRE EXTINGUISHER', 'NO-PARKING & TWILIGHT ZONE', 'BREAKING A NEW YEAR\'S RESOLUTION', 'STRUMMING A SONG ON A UKULELE', 'SENSATIONAL SUBMARINE SANDWICH', 'INVIGORATING MORNING SWIM'];
